#!/bin/zsh

# Builds the site and generates PDFs for articles
#./generate-pdfs

# upload the site to the server
# Shell alias for the below command
# "rsync -aP -e 'ssh -p 32000' /my/local/path/AdmiralBumbleBee.com/_site/ uesr@myserver.com:/var/www/admiralbumblebee.com/"
rsync -aP -e 'ssh' /Users/robertrandolph/Documents/AdmiralBumbleBee.com/_site/ bumbly@104.248.230.128:/var/www/admiralbumblebee.com/admiralbumblebee.com/
