  window.addEventListener('DOMContentLoaded', function(event) {
  // If you came here to read this, consider how much fun you just deprived yourself of.
  var randomSayingsFor_fun = [
      "Spending too much time on things that don't matter",
      "Things that you want which you can't find anywhere else",
      "Another day, another DAWller...?",
      "Can you believe this guy spends his time on this?",
      "Ableton Live, a Music Tech Elitist's worst enemy",
      "Reaper 5.99999991 - Coming soon!",
      "I don't have a license. My name is not Jack.",
      "100% Vanilla javascript, and a sprinkle of Ruby.",
      "If you're learning from ME, then you're in trouble",
      "Written in Emacs, the same way our forefathers wrote.",
      "Now Listening to - (ERROR: Please insert floppy disk)",
      "Powered by Parenthesis™",
      "AdmiralBumbleBee - what a silly name, ain't it?",
      "I once read part of a Nassim Nicholas Taleb book, so you know I'm probably smart",
      "Klicken Sie hier, bitte.",
      "Smalltalk did it 40 years ago, dude",
      "1c-b(1). Like, if you're about to pitch and then don't pitch, you have to still pitch. You cannot not pitch. Does that make any sense?",
      "Now on Twitter and Youtube!",
      "Ripped to shreds by REASON and LOGIC",
      "Thanks for reading! Sorry.",
      "The 100th commenter wins a Toy Yoda",
      "Dragon kings live beyond power laws",
      "I am trained in gorilla warfare and I’m the top sniper in the entire US armed forces.",
      "\phi (t+T)=\phi (t)\phi ^{{-1}}(0)\phi (T).",
      "RFC 20 - Status Code 808: Too much bass.",
      "Which way did he go, George?",
      "This site is tuned to 432hz for your enlightenment",
      "ISTJ-A - You can't argue, it's science.",
      "I remember when Common Lisp got that feature... in the 80s",
      "Status Code 218 - This is fine",
      "If my cert is expired, just e-mail me... my perl scripts are gross.",
      "This tagline is part of a long rant. Click for more.",
      "Oh oh oh, another Rust article on HN. How... exciting. meh.",
      "1) You can't just be up there and just doin' a balk like that.",
      "Wonder what they're arguing about on Gearslutz today?",
      "Wonder what they're arguing about on The Gear Page today?",
      "Wonder what they're arguing about on KVR today?",
      "Wonder what they're arguing about on VI-Control today?",
      "Peter Kirn is kinda cute.",
      "Visual programming... what a laugh.",
      "Another ALGOL syntax... alright, I guess. It worked the first time right?",
      "I know you checked the page source, don't lie.",
      "Xah Lee, the most irritatingly useful person on the internet",
      "The plural of regex is regrets",
      "My wife likes durian too much, it's a struggle for this dude.",
      "Some days the sun sneaks up on you real quick.",
      "Either you'll never be as good as you want to be, or you'll never be any good at all.",
      "If you told me 25 years ago I'd be playing Ibanez and MTD, I'd hit you.",
      "Let's go Gwang-ju.",
      "You're damn right I got a gun on me. Y'all going to steal my gun too?",
      "I'm just a vacuum cleaner salesman with a psychology degree."
  ];
      document.getElementById("wisdom").innerHTML = randomSayingsFor_fun[Math.floor((Math.random() * randomSayingsFor_fun.length))];
  }
    , false);